name: k3s-test-matrix

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read


jobs:
  docker:
    name: check-docker
    runs-on: [actuated-2cpu-6gb, n100]

    steps:
      - uses: actions/checkout@v4
      - name: Setup mirror
        uses: self-actuated/hub-mirror@master

      - name: Download check script from moby
        run: |
          curl -SLsfO https://raw.githubusercontent.com/moby/moby/refs/heads/master/contrib/check-config.sh
          chmod +x ./check-config.sh

      - name: Run check script
        run: |
          ./check-config.sh
          echo $?
  k3s:
    name: check-k3s
    runs-on: [actuated-2cpu-6gb, n100]

    steps:
      - uses: actions/checkout@v4
      - name: Setup mirror
        uses: self-actuated/hub-mirror@master

      - uses: alexellis/arkade-get@master
        with:
          print-summary: false
          k3sup: latest

      - name: Check the Kernel config
        run: |
          sudo -E $HOME/.arkade/bin/k3s check-config
